/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mavenproject.mavenproject1.INTERFACES.ESTUDIANTES;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import static mavenproject.mavenproject1.CLASES.AppState.serializar;
import mavenproject.mavenproject1.CLASES.Asignatura;
import static mavenproject.mavenproject1.CLASES.Asignatura.listadoAsignaturas;
import mavenproject.mavenproject1.CLASES.Estudiante;
import static mavenproject.mavenproject1.CLASES.Estudiante.listadoEstudiantes;
import mavenproject.mavenproject1.CLASES.Notas;
import mavenproject.mavenproject1.INTERFACES.ActualizarUsuario;
import mavenproject.mavenproject1.INTERFACES.LoginVentana;

/**
 *
 * @author angel
 */
public class EstudiantesVentana extends javax.swing.JFrame {

    int codigoUsuario;
    Estudiante es;
    
    public EstudiantesVentana(int codigoEstudiante) {
        initComponents();
        this.codigoUsuario = codigoEstudiante;
        this.es = enlace_CodigoEstu(this.codigoUsuario);
        jPanel2.setLayout(new GridLayout(30, 0));
        this.BotonesDinamicos();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
    }
    
    public Estudiante enlace_CodigoEstu(int codigo){
        for (Estudiante e : listadoEstudiantes) {
            if (e.codigo == codigo) {
                return e;
            }
        }
        return null;
    }
    
    public void BotonesDinamicos(){
        for (Asignatura curso : listadoAsignaturas) {
            for (Notas integrante : curso.integrantes) {
                if(integrante.estudiante == this.codigoUsuario){
                    crearBotones(curso);
                }
            }
        }
    }
     
            
    int index = 0;
    
    public void crearBotones(Asignatura curso){
        JButton botonCurso = new JButton(curso.nombre);
        JLabel numEs = new JLabel(curso.integrantes.size()+" estudiantes");
        botonCurso.setBounds(20, 20 + 80*index + 20*index, 250, 80);
        // Agregar una accion al presionar el boton
        botonCurso.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("hola");
                AdminCursoVentana acceder = new AdminCursoVentana(curso, codigoUsuario);
            }
        });
        numEs.setBounds(120, 90 + 80*index + 20*index, 100, 30);
        this.jPanel2.add(botonCurso);
        this.jPanel2.add(numEs);
        this.index += 1;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegresarLogin = new javax.swing.JButton();
        ActualizarButtom = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        RegresarLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegresarLogin.setForeground(new java.awt.Color(0, 0, 0));
        RegresarLogin.setText("Regresar al inicio de sesión");
        RegresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarLoginActionPerformed(evt);
            }
        });

        ActualizarButtom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ActualizarButtom.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarButtom.setText("Actualizar datos de Usuario");
        ActualizarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtomActionPerformed(evt);
            }
        });

        Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        Scroll.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegresarLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Scroll)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(ActualizarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarLoginActionPerformed
        LoginVentana regresarVentanaL = new LoginVentana();
        serializar();
        this.dispose();
    }//GEN-LAST:event_RegresarLoginActionPerformed

    private void ActualizarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtomActionPerformed
        ActualizarUsuario accederActualizar = new ActualizarUsuario(null, this.es);
    }//GEN-LAST:event_ActualizarButtomActionPerformed
    
    /**
     * @param args the command line arguments
     */
    private EstudiantesVentana() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudiantesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudiantesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudiantesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudiantesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudiantesVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButtom;
    private javax.swing.JButton RegresarLogin;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
