
package com.mycompany.practica2_gestiondelivery.interfaces;

import com.mycompany.practica2_gestiondelivery.AppState;

public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Ventana de Bienvenida");
        this.setDefaultCloseOperation(AdminFrame.EXIT_ON_CLOSE);
        this.instrucciones.setEditable(false);
        
        // rellenado de datos
        AppState.deserializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productoButtom = new javax.swing.JButton();
        PedidoButtom = new javax.swing.JButton();
        salirButtom = new javax.swing.JButton();
        HistorialButtom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instrucciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        productoButtom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productoButtom.setForeground(new java.awt.Color(0, 0, 0));
        productoButtom.setText("Agregar Productos");
        productoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoButtomActionPerformed(evt);
            }
        });

        PedidoButtom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PedidoButtom.setForeground(new java.awt.Color(0, 0, 0));
        PedidoButtom.setText("Realizar Pedido");
        PedidoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoButtomActionPerformed(evt);
            }
        });

        salirButtom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salirButtom.setForeground(new java.awt.Color(0, 0, 0));
        salirButtom.setText("Salir del Programa");
        salirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtomActionPerformed(evt);
            }
        });

        HistorialButtom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HistorialButtom.setForeground(new java.awt.Color(0, 0, 0));
        HistorialButtom.setText("Historial de Pedidos");
        HistorialButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialButtomActionPerformed(evt);
            }
        });

        instrucciones.setBackground(new java.awt.Color(204, 255, 204));
        instrucciones.setColumns(20);
        instrucciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        instrucciones.setForeground(new java.awt.Color(0, 0, 0));
        instrucciones.setLineWrap(true);
        instrucciones.setRows(5);
        instrucciones.setText("Importante:\n\nque durante todo el programa no se presione la \"x\" en la parte superior derecha de la ventana, para regresar una ventana tendrá un botón disponible que diga \"Regresar\" o \"cancelar\" según sea el caso y la acción.");
        jScrollPane1.setViewportView(instrucciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PedidoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HistorialButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PedidoButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HistorialButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtomActionPerformed
        AppState.serializar();
        System.exit(0);
    }//GEN-LAST:event_salirButtomActionPerformed

    private void productoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoButtomActionPerformed
        ProductosFrame productos = new ProductosFrame();
        this.dispose();
    }//GEN-LAST:event_productoButtomActionPerformed

    private void PedidoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoButtomActionPerformed
        PedidosFrame pedidos = new PedidosFrame();
        this.dispose();
    }//GEN-LAST:event_PedidoButtomActionPerformed

    private void HistorialButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialButtomActionPerformed
        HistorialFrame historial = new HistorialFrame();
        this.dispose();
    }//GEN-LAST:event_HistorialButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistorialButtom;
    private javax.swing.JButton PedidoButtom;
    private javax.swing.JTextArea instrucciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton productoButtom;
    private javax.swing.JButton salirButtom;
    // End of variables declaration//GEN-END:variables
}
